name: Fetch upstream from Ajaxy/telegram-tt
on: 
  schedule:
    - cron: '0 0 1 * *'
    # scheduled for 00:00 every first day of the month

  workflow_dispatch:
    inputs:
      upstream:
        description: 'Upstream repository Ajaxy/telegram-tt.'
        required: true
        default: 'Ajaxy/telegram-tt'       # set the upstream repo
      upstream-branch:
        description: 'Upstream branch to merge from.'
        required: true
        default: 'master'           # set the upstream branch to merge from
      branch:
        description: 'Branch to merge to'
        required: true
        default: 'upstream_sync'         # set the branch to merge to

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0 
      - name: Merge Upstream (Cubik65536's Fork)
        uses: Cubik65536/merge-upstream@v1.1.3
        with:
          upstream: ${{ github.event.inputs.upstream }}
          upstream-branch: ${{ github.event.inputs.upstream-branch }}
          branch: ${{ github.event.inputs.branch }}
          token: ${{ secrets.TOKEN }}
  # Create a pull request from the fetched commits
  auto-pull-request:
    needs: merge-upstream
    runs-on: ubuntu-latest
    steps:
      - name: pull-request-action
        uses: vsoch/pull-request-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_BRANCH: "master"
          PULL_REQUEST_TITLE: "Fetching Upstream changes from Ajaxy/telegram-tt"
          PULL_REQUEST_BODY: "This is an automated PR that fetches new commits from `Ajaxy/telegram-tt` that are updated in the `upstream_sync` branch."
          PULL_REQUEST_UPDATE: true
          PULL_REQUEST_FROM_BRANCH: "upstream_sync"
